# Site settings
title: Blog BSource
description: Um blog sobre tecnologia em especial o framework Ext JS
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.bsource.com.br" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Daniel da Cunha Bueno 
user_description: Senior Software Enginer em aplicações web e mobile (#C,Sencha Ext JS, Xamarin).
email: 
twitter_username: BSourceSistemas
github_username:  bsourcesistemas
linkedin_username: bsource
gplus_username:  lorem_ipsum
disqus_username: lorem_ipsum

# User settings 2
#username2: Dalton Eduardo da Silveira
user_description: Senior Software Enginer em aplicações web e mobile (#C,Sencha Ext JS, Xamarin).
email: 
twitter_username: BSourceSistemas
github_username:  bsourcesistemas
linkedin_username: linkedin_username
gplus_username:  lorem_ipsum
disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: 
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: Sobre 
    url: /about
  - title: Contato
    url: /contato 
  - title: Newsletter
    url: /newsletter
    
# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']

# Disqus Comments
disqus:
  shortname: bsourcesistemas

# coleção de colaboradores do site 
collections:
  authors:
  output: true 

#Schedule 

future: false

#multilanguage
gem: 'jekyll-multiple-languages-plugin'

#setup multilanguage

url: https://blog.bsource.com.br

languages: ["en", "de"]
exclude_from_localizations: ["assets", "CNAME"]
defaultLang: en
languageNames:
  de: Deutsch
  en: English

# Google Analytics
google_analytics: UA-85665246-1


